version: '0.1'

services:
  result:
    image: result-app
    container_name: result-container
    build:
      context: ./result
    ports:
      - "8081:8081"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    restart: always

  vote:
    image: vote-app
    container_name: vote-container
    build:
      context: ./vote
    ports:
      - "8080:8080"
    networks:
      - appnet
    depends_on:
      - postgres
    restart: always

  worker:
    image: worker-app
    container_name: worker-container
    build:
      context: ./worker
    networks:
      - appnet
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - appnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - appnet
    restart: always

networks:
  appnet:
    driver: bridge

volumes:
  postgres-data: