version: '1'

services:

  vote:
    image: vote-app
    build:
      context: ./vote
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    depends_on:
      - redis

  result:
    image: result-app
    build:
      context: ./result
    ports:
      - "8081:8081"
    networks:
      - frontend
      - backend
    depends_on:
      - db

  worker:
    image: worker-app
    build:
      context: ./worker
    networks:
      - backend
    depends_on:
      - db
      - redis
  
  redis:
    image: redis
    container_name: redis-container
    networks:
      - backend

  db:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend
    volumes:
      - "db-data:/var/lib/postgresql/data"

networks:
  frontend:
  backend:

volumes:
  db-data: