version: '3.7'

services:

  vote:
    image: marwenmeddeb/voteapp
    ports:
      - 8080:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result:
    image: marwenmeddeb/resultapp
    ports:
      - 8081:80
    networks:
      - backend
    deploy:
      replicas: 2

  worker:
    image: marwenmeddeb/workerapp
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2


  redis:
    image: redis
    networks:
      - frontend

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend

networks:
  frontend:
  backend: