version: '3.8'

services:

  redis:
    image: redis
    networks:
      - backend
    deploy:
      replicas: 1 

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - post-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1


  vote:
    image: marwenmeddeb/voteapp
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    deploy:
      replicas: 3


  result:
    image: marwenmeddeb/resultapp
    ports:
      - 8081:80
    networks:
      - frontend
      - backend
    depends_on:
      - db
    deploy:
      replicas: 3

  worker:
    image: marwenmeddeb/workerapp
    networks:
      - backend
    deploy:
      replicas: 3

        
networks:
  frontend:
  backend:

volumes:
  post-data: